[package]
name = "parser_test"
version.workspace = true

description.workspace = true
include.workspace = true
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustpython-parser = {path = "../parser"}